spring.application.name=cuss
spring.datasource.url=jdbc:postgresql://localhost:5432/kiosk
spring.datasource.username=postgres
spring.datasource.password=devtest2202
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false